[2024-11-10T13:07:37.847+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-10T13:07:37.878+0000] {taskinstance.py:2603} INFO - Dependencies not met for <TaskInstance: dag_with_postgres_operator_v03.create_postgres_table scheduled__2021-12-27T00:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2024-11-10T13:07:37.887+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
