[2024-11-10T15:27:44.076+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-10T15:27:44.105+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_dag_with_duration.merge_df1_with_df2 manual__2024-11-10T15:21:57.162279+00:00 [queued]>
[2024-11-10T15:27:44.121+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_dag_with_duration.merge_df1_with_df2 manual__2024-11-10T15:21:57.162279+00:00 [queued]>
[2024-11-10T15:27:44.123+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-10T15:27:44.154+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): merge_df1_with_df2> on 2024-11-10 15:21:57.162279+00:00
[2024-11-10T15:27:44.167+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=505) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-10T15:27:44.171+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_dag_with_duration', 'merge_df1_with_df2', 'manual__2024-11-10T15:21:57.162279+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_dag.py', '--cfg-path', '/tmp/tmphvbfhz2l']
[2024-11-10T15:27:44.173+0000] {standard_task_runner.py:105} INFO - Job 140: Subtask merge_df1_with_df2
[2024-11-10T15:27:44.172+0000] {standard_task_runner.py:72} INFO - Started process 514 to run task
[2024-11-10T15:27:44.268+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline_dag_with_duration.merge_df1_with_df2 manual__2024-11-10T15:21:57.162279+00:00 [running]> on host 1669fe1f842b
[2024-11-10T15:27:44.415+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline_dag_with_duration' AIRFLOW_CTX_TASK_ID='merge_df1_with_df2' AIRFLOW_CTX_EXECUTION_DATE='2024-11-10T15:21:57.162279+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-10T15:21:57.162279+00:00'
[2024-11-10T15:27:44.417+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-10T15:27:44.418+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-10T15:27:44.418+0000] {logging_mixin.py:190} INFO - Current task name:merge_df1_with_df2 state:running start_date:2024-11-10 15:27:44.108073+00:00
[2024-11-10T15:27:44.419+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline_dag_with_duration and current dag run status:running
[2024-11-10T15:27:44.421+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-10T15:27:44.424+0000] {logging_mixin.py:190} INFO - Simulating task for 5 seconds.
[2024-11-10T15:27:49.425+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-10T15:27:49.441+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-10T15:27:49.442+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline_dag_with_duration, task_id=merge_df1_with_df2, run_id=manual__2024-11-10T15:21:57.162279+00:00, execution_date=20241110T152157, start_date=20241110T152744, end_date=20241110T152749
[2024-11-10T15:27:49.473+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-10T15:27:49.474+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-10T15:27:49.475+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline_dag_with_duration queued_at:2024-11-10 15:21:57.300030+00:00
[2024-11-10T15:27:49.476+0000] {logging_mixin.py:190} INFO - Task hostname:1669fe1f842b operator:PythonOperator
[2024-11-10T15:27:49.527+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-10T15:27:49.574+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-10T15:27:49.583+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
